apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-docker-k8s-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-docker-k8s
  template:
    metadata:
      labels:
        app: demo-docker-k8s
    spec:
      containers:
      - name: demo-docker-k8s-container
        image: bwanwork1/demo-docker-k8s:latest  # Replace with your image if pushed to a registry
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-docker-k8s-app-service
spec:
  selector:
    app: demo-docker-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Or LoadBalancer for cloud environments
